theme: jekyll-theme-minimal
title: Welcome to Cami Brumar's homepage!
description: Feel free to bookmark this to keep an eye on my progress on Data Visualization homework/artworks :P
include:
  - "darth_vader.png"
